[package]
name = "nme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = {version = "0.27.0", features = ['serde']}
ratatui = "0.25.0"
serde = {version = "1.0", features = ['derive']}
toml = "0.8.8"
